name: Release

on: 
  workflow_dispatch:
    inputs:
      username:
        description: Github username of the person triggering the release
        default: "sergey-tihon"
        required: true

jobs:
  release:
    # this workflow is the same as the build workflow, up until artifact upload + publish
    runs-on: macos-latest

    steps:
    # manual triggers are detached HEADs, so we need to checkout the branch
    # to actually create + push a commit later on in the workflow
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '15.12.0'
    - name: Restore local tools
      run: dotnet tool restore
    - name: Paket Restore
      run: dotnet paket restore
    - name: Install VSCE
      run: yarn global add vsce
    - name: Publish Release
      env:
        vsce-token: ${{ secrets.VSCE_TOKEN }}
      run: dotnet fake build -t Release
    - name: upload artifact package
      uses: actions/upload-artifact@v2
      with:
        name: openxml-explorer-vscode-ext
        path: release/